---
title: Avram Schema Format
description: JSON Schema of Avram Schema Format to validata Avram Schemas
type: object
additionalProperties: false
properties:
  title:
    type: string
  description:
    type: string
  url:
    type: string
    format: uri
  profile:
    type: string
    format: uri
  $schema:
    type: string
    format: uri
  fields:
    $ref: '#/definitions/field-schedule'
  deprecated-fields:
    $ref: '#/definitions/field-schedule'
  count:
    type: integer
    minimum: 0
  language:
    type: string
    pattern: '^[a-zA-Z]{1,8}(-[a-zA-Z0-9]{1,8})*$'
required:
  - fields
definitions:
  url:
    type: string
    format: uri
  timestamp:
    type: string
  field-schedule:
    type: object
    patternProperties:
      '^.+$':
        type: object
        additionalProperties: false
        properties:
          tag:
            type: string
          label:
            type: string
          description:
            type: string
          repeatable:
            type: boolean
          required:
            type: boolean
          pattern:
            type: string
          url:
            $ref: '#/definitions/url'
          occurrence:
            type: string
          indicator1:
            $ref: '#/definitions/indicator'
          indicator2:
            $ref: '#/definitions/indicator'
          pica3:
            type: string
          subfields:
            $ref: '#/definitions/subfield-schedule'
          deprecated-subfields:
            $ref: '#/definitions/subfield-schedule'
          positions:
            $ref: '#/definitions/positions'
          types:
            $ref: '#/definitions/field-types'
          modified:
            $ref: '#/definitions/timestamp'
  positions:
    type: object
    patternProperties:
      '^[0-9]+(-[0-9]+)?$':
        $ref: '#/definitions/codedvalue'
  field-types:
    oneOf:
      - type: object
        patternProperties:
          '^.*$':
            type: object
            additionalProperties: false
            properties:
              positions:
                $ref: '#/definitions/positions'
            required:
             - positions
      - type: object
        patternProperties:
          '^.*$':
            type: object
            additionalProperties: false
            properties:
              subfields:
                $ref: '#/definitions/subfield-schedule'
            required:
             - subfields
  subfield-schedule:
    type: object
    additionalProperties: false
    properties:
      code:
        type: string
      label:
        type: string
      description:
        type: string
      repeatable:
        type: boolean
      required:
        type: boolean
      url:
        $ref: '#/definitions/url'
      order:
        type: integer
      positions:
        $ref: '#/definitions/positions'
      pica3:
        type: string
      modified:
        $ref: '#/definitions/timestamp'
  indicator:
    oneOf:
      - type: 'null'
      - $ref: '#/definitions/codedvalue'
  codedvalue:
    type: object
    additionalProperties: false
    properties:
      label:
        type: string
      description:
        type: string
      url:
        $ref: '#/definitions/url'
      codes:
        $ref: '#/definitions/codelist'
      pattern:
        type: string
      deprecated-codes:
        $ref: '#/definitions/codelist'
  codelist:
    type: object
    patternProperties:
      '^.+$':
        additionalProperties: false
        properties:
          label:
            type: string
          description:
            type: string
$schema: http://json-schema.org/draft-06/schema#
