---
title: Avram Schema Format
description: JSON Schema of Avram Schema Format to validata Avram Schemas
type: object
additionalProperties: false
properties:
  title:
    type: string
  description:
    type: string
  url:
    type: string
    format: uri
  profile:
    type: string
    format: uri
  $schema:
    type: string
    format: uri
  fields:
    $ref: '#/definitions/field-schedule'
  deprecated-fields:
    $ref: '#/definitions/field-schedule'
  count:
    $ref: '#/definitions/non-negative-integer'
    description: 'deprecated, use "records" instead!'
  records:
    $ref: '#/definitions/non-negative-integer'
  language:
    type: string
    pattern: '^[a-zA-Z]{1,8}(-[a-zA-Z0-9]{1,8})*$'
required:
  - fields
definitions:
  url:
    type: string
    format: uri
  timestamp:
    type: string
  non-negative-integer:
    type: integer
    minimum: 0
  field-schedule:
    type: object
    patternProperties:
      '^.+$':
        type: object
        additionalProperties: false
        properties:
          tag:
            type: string
          label:
            type: string
          occurrence:
            type: string
            pattern: '^[0-9][0-9](-[0-9][0-9])?$'
          counter:
            type: string
            pattern: '^[0-9]+(-[0-9]+)?$'
          description:
            type: string
          repeatable:
            type: boolean
          required:
            type: boolean
          pattern:
            type: string
          url:
            $ref: '#/definitions/url'
          indicator1:
            $ref: '#/definitions/indicator'
          indicator2:
            $ref: '#/definitions/indicator'
          pica3:
            type: string
          subfields:
            $ref: '#/definitions/subfield-schedule'
          deprecated-subfields:
            $ref: '#/definitions/subfield-schedule'
          positions:
            $ref: '#/definitions/positions'
          types:
            $ref: '#/definitions/field-types'
          modified:
            $ref: '#/definitions/timestamp'
          total:
            $ref: '#/definitions/non-negative-integer'
          records:
            $ref: '#/definitions/non-negative-integer'
  positions:
    type: object
    patternProperties:
      '^[0-9]+(-[0-9]+)?$':
        $ref: '#/definitions/codedvalue'
  field-types:
    oneOf:
      - type: object
        patternProperties:
          '^.*$':
            type: object
            additionalProperties: false
            properties:
              positions:
                $ref: '#/definitions/positions'
            required:
             - positions
      - type: object
        patternProperties:
          '^.*$':
            type: object
            additionalProperties: false
            properties:
              subfields:
                $ref: '#/definitions/subfield-schedule'
            required:
             - subfields
  subfield-schedule:
    type: object
    additionalProperties: false
    properties:
      code:
        type: string
      label:
        type: string
      description:
        type: string
      repeatable:
        type: boolean
      required:
        type: boolean
      url:
        $ref: '#/definitions/url'
      order:
        type: integer
      positions:
        $ref: '#/definitions/positions'
      codes:
        $ref: '#/definitions/codelist'
      pica3:
        type: string
      modified:
        $ref: '#/definitions/timestamp'
      total:
        $ref: '#/definitions/non-negative-integer'
      records:
        $ref: '#/definitions/non-negative-integer'
  indicator:
    oneOf:
      - type: 'null'
      - $ref: '#/definitions/codedvalue'
  codedvalue:
    type: object
    additionalProperties: false
    properties:
      label:
        type: string
      description:
        type: string
      url:
        $ref: '#/definitions/url'
      codes:
        $ref: '#/definitions/codelist'
      pattern:
        type: string
      deprecated-codes:
        $ref: '#/definitions/codelist'
  codelist:
    oneOf:
      - type: string
        format: uri
      - type: object
        patternProperties:
          '^.+$':
            additionalProperties: false
            properties:
              label:
                type: string
              description:
                type: string
              total:
                $ref: '#/definitions/non-negative-integer'
              records:
                $ref: '#/definitions/non-negative-integer'
$schema: http://json-schema.org/draft-06/schema#
